import enum


class Genre(enum.Enum):
    Alternative = "Alternative"
    Blues = "Blues"
    Classical = "Classical"
    Country = "Country"
    Electronic = "Electronic"
    Folk = "Folk"
    Funk = "Funk"
    Hip_Hop = "Hip-Hop"
    Heavy_Metal = "Heavy Metal"
    Instrumental = "Instrumental"
    Jazz = "Jazz"
    Musical_Theatre = "Musical Theatre"
    Pop = "Pop"
    Punk = "Punk"
    R_n_B = "R&B"
    Reggae = "Reggae"
    Rock_n_Roll = "Rock n Roll"
    Soul = "Soul"
    Swing = "Swing"
    Other = "Other"

    @classmethod
    def choices(cls):
        return [(choice.name, choice.value) for choice in cls]


class State(enum.Enum):
    AL = "AL"
    AK = "AK"
    AZ = "AZ"
    AR = "AR"
    CA = "CA"
    CZ = "CZ"
    CO = "CO"
    CT = "CT"
    DE = "DE"
    DC = "DC"
    FL = "FL"
    GA = "GA"
    GU = "GU"
    HI = "HI"
    ID = "ID"
    IL = "IL"
    IN = "IN"
    IA = "IA"
    KS = "KS"
    KY = "KY"
    LA = "LA"
    ME = "ME"
    MD = "MD"
    MA = "MA"
    MI = "MI"
    MN = "MN"
    MS = "MS"
    MO = "MO"
    MT = "MT"
    NE = "NE"
    NV = "NV"
    NH = "NH"
    NJ = "NJ"
    NM = "NM"
    NY = "NY"
    NC = "NC"
    ND = "ND"
    OH = "OH"
    OK = "OK"
    OR = "OR"
    PA = "PA"
    PR = "PR"
    RI = "RI"
    SC = "SC"
    SD = "SD"
    TN = "TN"
    TX = "TX"
    UT = "UT"
    VT = "VT"
    VI = "VI"
    VA = "VA"
    WA = "WA"
    WV = "WV"
    WI = "WI"
    WY = "WY"

    @classmethod
    def choices(cls):
        return [(choice.name, choice.value) for choice in cls]
